#!/usr/bin/env python3
"""
gen_reg_toggle_cfg.py — derive the register-bit-toggle coverage config from the IP's
SystemRDL, so the reusable `reg_bit_toggle_cov` collector needs no hand-listed names.

Today it extracts one thing: the `singlepulse` fields. Such a field holds a written 1 for
exactly one clock and then self-clears, so a bus read can NEVER observe it as 1 (by
design, not a stimulus gap). The collector therefore credits their rise from the
accepted write of 1 and their fall from the next read that returns 0, instead of
waiting forever for a read of 1.

Usage (needs the project venv, which carries systemrdl-compiler):
    env/.venv/bin/python3 flow/scripts/gen_reg_toggle_cfg.py ips/<ip>
Reads   ips/<ip>/ip_config.yaml  registers.source   (e.g. rdl/<ip>.rdl)
Writes  ips/<ip>/dv/sv/env/<ip>_reg_toggle_cfg.svh
"""
import re, sys
from pathlib import Path

try:
    from systemrdl import RDLCompiler
    from systemrdl.node import FieldNode
except ImportError:
    sys.exit("systemrdl-compiler not found -- run with env/.venv/bin/python3 (see env/bootstrap-wsl2.sh)")


def rdl_source(ip_dir: Path) -> Path:
    cfg = (ip_dir / "ip_config.yaml").read_text()
    m = re.search(r"^registers:\s*\n(?:\s+.*\n)*?\s+source:\s*(\S+)", cfg, re.M)
    if not m:
        sys.exit(f"no registers.source in {ip_dir}/ip_config.yaml")
    return ip_dir / m.group(1)


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_reg_toggle_cfg.py ips/<ip>")
    ip_dir = Path(sys.argv[1]).resolve()
    ip = ip_dir.name
    src = rdl_source(ip_dir)

    rdlc = RDLCompiler()
    rdlc.compile_file(str(src))
    root = rdlc.elaborate()

    pulse = []          # "<reg>.<field>" suffixes, unique (a regfile instantiated N times
    for node in root.descendants():                 # yields the same suffix N times)
        if isinstance(node, FieldNode) and node.get_property("singlepulse"):
            key = f"{node.parent.inst_name}.{node.inst_name}"
            if key not in pulse:
                pulse.append(key)

    out = ip_dir / "dv" / "sv" / "env" / f"{ip}_reg_toggle_cfg.svh"
    body = ", ".join(f'"{p}"' for p in pulse)
    out.write_text(
        f"// AUTO-GENERATED by flow/scripts/gen_reg_toggle_cfg.py from {src.relative_to(ip_dir)}"
        " -- do not hand-edit; re-run instead.\n"
        "// SystemRDL `singlepulse` fields, as \"<reg>.<field>\" suffixes of the RAL field full\n"
        "// name (a regfile instantiated N times matches all N instances). reg_bit_toggle_cov\n"
        "// credits their rise from the accepted write of 1 and their fall from the next read\n"
        "// of 0, because a bus read can never observe a one-cycle pulse as 1.\n"
        f"function automatic void {ip}_reg_pulse_fields(ref string q[$]);\n"
        + (f"    q = '{{{body}}};\n" if pulse else "    q.delete();\n")
        + "endfunction\n", newline="\n")
    print(f"wrote {out}  ({len(pulse)} singlepulse field(s): {', '.join(pulse) or 'none'})")


if __name__ == "__main__":
    main()
