// AUTO-GENERATED by flow/scripts/gen_reg_toggle_cfg.py from rdl/pmtpc4.rdl -- do not hand-edit; re-run instead.
// SystemRDL `singlepulse` fields, as "<reg>.<field>" suffixes of the RAL field full
// name (a regfile instantiated N times matches all N instances). reg_bit_toggle_cov
// credits their rise from the accepted write of 1 and their fall from the next read
// of 0, because a bus read can never observe a one-cycle pulse as 1.
function automatic void pmtpc4_reg_pulse_fields(ref string q[$]);
    q = '{"CTRL.SOFT_RESET", "CH_CTRL.CH_START"};
endfunction
